# Generated by Django 4.2.16 on 2024-11-16 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_servicecategory_subservice_specificservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='portfolio_images',
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='users.servicecategory'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='specific_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='users.specificservice'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='sub_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='users.subservice'),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolios/')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='users.serviceproviderprofile')),
            ],
        ),
    ]
